export type District = string;
export type Province = {
  name: string;
  districts: District[];
};

export const MOZAMBIQUE_LOCATIONS: Province[] = [
  {
    name: "Cabo Delgado",
    districts: [
      "Ancuabe",
      "Balama",
      "Chiúre",
      "Ibo",
      "Macomia",
      "Mecúfi",
      "Meluco",
      "Metuge",
      "Mocímboa da Praia",
      "Montepuez",
      "Mueda",
      "Muidumbe",
      "Namuno",
      "Nangade",
      "Palma",
      "Pemba City",
      "Quissanga",
    ],
  },
  {
    name: "Gaza",
    districts: [
      "Bilene",
      "Chibuto",
      "Chicualacuala",
      "Chigubo",
      "Chókwè",
      "Chongoene",
      "Guijá",
      "Limpopo",
      "Mabalane",
      "Manjacaze",
      "Mapai",
      "Massangena",
      "Massingir",
      "Xai-Xai City",
      "Xai-Xai District",
    ],
  },
  {
    name: "Inhambane",
    districts: [
      "Funhalouro",
      "Govuro",
      "Homoíne",
      "Inhambane City",
      "Inharrime",
      "Inhassoro",
      "Jangamo",
      "Mabote",
      "Massinga",
      "Maxixe City",
      "Morrumbene",
      "Panda",
      "Vilankulo",
      "Zavala",
    ],
  },
  {
    name: "Manica",
    districts: [
      "Bárue",
      "Chimoio City",
      "Gondola",
      "Guro",
      "Macate",
      "Machaze",
      "Macossa",
      "Manica",
      "Mossurize",
      "Sussundenga",
      "Tambara",
      "Vanduzi",
    ],
  },
  {
    name: "Maputo City",
    districts: [
      "KaMpfumo",
      "KaNhlamankulu",
      "KaMaxaquene",
      "KaMavota",
      "KaMubukwana",
      "KaTembe",
      "KaNyaka",
    ],
  },
  {
    name: "Maputo Province",
    districts: [
      "Boane",
      "Magude",
      "Manhiça",
      "Marracuene",
      "Matola City",
      "Matutuíne",
      "Moamba",
      "Namaacha",
    ],
  },
  {
    name: "Nampula",
    districts: [
      "Angoche",
      "Eráti",
      "Ilha de Moçambique",
      "Lalaua",
      "Larde",
      "Liúpo",
      "Malema",
      "Meconta",
      "Mecubúri",
      "Memba",
      "Mogincual",
      "Mogovolas",
      "Moma",
      "Monapo",
      "Mossuril",
      "Muecate",
      "Murrupula",
      "Nacala-a-Velha",
      "Nacala Porto",
      "Nampula City",
      "Rapale",
      "Ribáuè",
    ],
  },
  {
    name: "Niassa",
    districts: [
      "Chimbonila",
      "Cuamba",
      "Lago",
      "Lichinga City",
      "Majune",
      "Mandimba",
      "Marrupa",
      "Maúa",
      "Mavago",
      "Mecanhelas",
      "Mecula",
      "Metarica",
      "Muembe",
      "N'gauma",
      "Sanga",
    ],
  },
  {
    name: "Sofala",
    districts: [
      "Beira City",
      "Búzi",
      "Caia",
      "Chemba",
      "Cheringoma",
      "Chibabava",
      "Dondo",
      "Gorongosa",
      "Machanga",
      "Maringué",
      "Marromeu",
      "Muanza",
      "Nhamatanda",
    ],
  },
  {
    name: "Tete",
    districts: [
      "Angónia",
      "Cahora-Bassa",
      "Changara",
      "Chifunde",
      "Chiuta",
      "Dôa",
      "Macanga",
      "Magoé",
      "Marara",
      "Marávia",
      "Moatize",
      "Mutarara",
      "Tete City",
      "Tsangano",
      "Zumbo",
    ],
  },
  {
    name: "Zambézia",
    districts: [
      "Alto Molócuè",
      "Chinde",
      "Derre",
      "Gilé",
      "Gurué",
      "Ile",
      "Inhassunge",
      "Luabo",
      "Lugela",
      "Maganja da Costa",
      "Milange",
      "Mocuba",
      "Mocubela",
      "Molumbo",
      "Mopeia",
      "Morrumbala",
      "Namacurra",
      "Namarroi",
      "Nicoadala",
      "Pebane",
      "Quelimane City",
    ],
  },
];
